### ISSUE TITLE
Bit Heroes: Create Content on what is going to be on Bit Heroes web page

### ISSUE THREAD

**Issue by beccatran** [bitprj/bitproject#125]
**Objectives: Write in detail on what the Bit Heroes Program is going to consist of**

**Collaborators and Tasks**
@shreyagupta98 
Marketing Specialist 

- [x] Write and "about" page explaining all the logistics of the program. Refer to the [doc](https://docs.google.com/document/d/15V64DvR6oWyybpyy_EbwcNTC4r6p-gmB_gL0YNjplRI/edit?usp=sharing)
- [x] Write out what the 8 week program consists 
- [x] Write out the application process 

**Deadline: May 14th or ASAP**

**Comment by shreythecray** [comment]
[High school program schedule](https://hackmd.io/@pTq-jFJXTBiSn0-nHPM5nw/BJDA_LLqU)
