### ISSUE TITLE
[DevRel Admin] Start to End Process of Curriculum

### ISSUE THREAD

**Issue by kavuong** [bitprj/bitproject#34]
**Objectives:**
To document the development and review process from start to end on GitBooks, all in one place with stages.

- [ ] Descriptions of Development
- [ ] Descriptions of Weekly Manager Review
- [ ] Descriptions of Review by Kevin
- [ ] Descriptions of Review by Daniel
- [ ] All descriptions highlighted with stages

**Collaborators:**
* @lazyplatypus 
* @kavuong 

**Deadlines:**

**Comment by lazyplatypus** [comment]
We should loop in @mxthu and Vicky especially to set guidelines on writing style and grammar
