### ISSUE TITLE
[DevRel Admin] Addressing Async Communication Issues

### ISSUE THREAD

**Issue by kavuong** [bitprj/bitproject#35]
**Objectives:**
- [x] Setting dedicated hours towards Bit
- [ ] Documenting the following on GitBooks
  - [x] follow-ups in communication in the channel 1 day before, and then daily follow-ups via DM after the due date, as well as a video call discussing problems
  - [x] setting deadlines
  - [ ] documenting admin task issues (template, process, adding deadlines to issues)
  
**Collaborators:**
@kavuong 

**Deadlines:**
documenting should be done Tuesday, 3/31

**Comment by lazyplatypus** [comment]
- [ ] documenting admin task issues (template, process, adding deadlines to issues)
