### ISSUE TITLE
Create Descriptions / Responsibilities for each position on Bit Project

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/bitproject#58]
**Objectives**
To clarify to prospects what roles are available in Bit Project and what each role entails. 

**Collaborators and Tasks**
@kavuong - DevRel Positions
- [ ] Head of DevRel
- [ ] Content Development Intern 
- [ ] Content Developer
- [ ] Content Development Manager

@shreyagupta98 - People Positions / Marketing Positions
- [x] Director of People 
- [x] Learning and Development Manager
- [x] People Experience Associate
- [x] Inclusion and Diversity Associate 
- [x] Onboarding Manager
- [x] Recruiter

- [ ] Director of Marketing
- [ ] Manager of Design
- [ ] Illustrator
- [ ] Manager of Technical Writing

@wongband  - Engineering Positions
- [ ] Director of Engineering
- [x] Frontend Architect 
- [x] React.js Developer
- [x] Backend Developer

**Deadline**
April 2nd

**Comment by lazyplatypus** [comment]
Each Position should look like this -> https://about.gitlab.com/job-families/engineering/software-engineer-intern/

**Comment by lazyplatypus** [comment]
> Do we have to put the hiring process and apply section?
<sub>[View in Slack](https://bitdarlene.slack.com/archives/DJ20YHGS0/p1585620475007900)</sub>

**Comment by lazyplatypus** [comment]
> No. Just focus on the other sections
<sub>[View in Slack](https://bitdarlene.slack.com/archives/DJ20YHGS0/p1585620515008600)</sub>

**Comment by kavuong** [comment]
@lazyplatypus Does the call with @shreyagupta98, you and I on Friday satisfy the "Content Developer" position?

**Comment by lazyplatypus** [comment]
Yes just write it down on gitbooks
