### ISSUE TITLE
Compile Medium Articles for Sunday's DevRel Town Hall

### ISSUE THREAD

**Issue by kavuong** [bitprj/bitproject#65]
**Objectives**
To curate a list of workshop ideas that our developers can draw inspiration from for their upcoming workshops.

- [x] Create and set-up Airtable
- [x] Confirm list of topics
- [x] Compile list of medium articles for each topic

**Collaborators and Tasks**
@lazyplatypus 
@kavuong 

**Deadline**
Saturday, 4/4

**Comment by lazyplatypus** [comment]
https://airtable.com/shrhsNcnQiwWA32EL
