### ISSUE TITLE
MDX Deck Documentation

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/bitproject#77]
**Objectives**
Get Documentation for MDX Deck.
- [x] Code Surfer
- [x] MDX Deck Documentation for All Slides Formats
- [x] MDX Deck Documentation in MDX Deck
- [x] Restyling Slides with Input from Rochelle

**Collaborators and Tasks**
@atuljayaram 

**Deadline**
Monday, 04/06/20

**Comment by atuljayaram** [comment]
> **Objectives**
> Get Documentation for MDX Deck.
> 
> * [x]  Code Surfer
> * [x]  MDX Deck Documentation for All Slides Formats
> * [ ]  MDX Deck Documentation in MDX Deck
> * [ ]  Restyling Slides with Input from Rochelle
> 
> **Collaborators and Tasks**
> @atuljayaram
> 
> **Deadline**
> Monday, 04/06/20

I've included a slide deck for Code Surfer but not for base MDX Deck yet.
